### PR TITLE
Development

### PR DESCRIPTION
**Pull request by maasencioh**
The initial state for the peak picking with baseline tracking

### CODE REVIEW

**Review by lpatiny — COMMENTED** [review]
Please generate a docs (using jsdoc) with an example so that we can easily test.

**Comment by targos** [comment]
the name should be "peak-picking"

**Comment by targos** [comment]
no, please don't generate the doc in this pull request. we cannot render it and it adds a lot of noise to the diff

**Comment by maasencioh** [comment]
@targos where is not called like `peak-picking`? and I strongly agree with avoid the jsdoc in here

**Comment by targos** [comment]
@maasencioh the directory is called like that

**Comment by lpatiny** [comment]
In the testcases you could check the surface of the peaks on the generated spectra ?

I'm also wondering what is the status of the spectra generator that @jobo322 was working on. it could be a dependency of this project for test cases.

**Comment by maasencioh** [comment]
@lpatiny with the surface you mean integration?

**Comment by lpatiny** [comment]
If you simulate a spectrum you know many information about the peak: height, position, and surface under the peak.
The same result should be found after peak picking and therefore the testcase seems to me.

**Comment by maasencioh** [comment]
@lpatiny but with surface you are talking about the integral of the function, I guess that I can calculate it based on the formula, but this is currently just the peak picking

**Pull request closed without merging**
